### ISSUE TITLE
Upgrade from 1.1.7 to 1.1.8 causing crash-loop on shared storage. 

### ISSUE THREAD

**Issue by KenBurk** [openappsec/smartsync-shared-files#4]
PR to add port 80 was actually a replace port 80. Breaking change.

**Comment by orianelou** [comment]
Hi @KenBurk, 

Could you please let us know which env you are using? NGINX or Kong?

Thank you!

**Comment by KenBurk** [comment]
We are using nginx

**Comment by nahum-perman** [comment]
Hi @KenBurk ,

have you downloaded the latest helm chart?

**Comment by KenBurk** [comment]
We did not, our charts have to be customized to set the proper namespace and storage configuration, so breaking changes are kind of a big deal.

**Comment by nahum-perman** [comment]
Hi @KenBurk ,

My sincere apologies, you can upgrade safely by adding 
--set appsec.learning.image.tag=1.1.7 --set appsec.storage.image.tag=1.1.7
to the upgrade command.
I will update once a BC image is available.

**Comment by nahum-perman** [comment]
backward compatible image is published
